defmodule AwesomeDashboard.Repo.Migrations.Initialize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:items, primary_key: false) do
      add :name, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:items)
  end
end